### PR TITLE
Add Extendify Library v10.3

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This adds the library for next gen patterns.

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Hey @munirkamal This is ready to merge when you have a chance to look at it. We had to fix a conflict with EK and the library and had to make a trivial change to EK.

`/includes/class-editorskit-block-assets.php` - line 125 and 129 we just rearranged the dependency order. 
`/includes/class-editorskit-welcome.php` - line 114 the same change.
`/plugin.php` - line 254 I added a new global variable

Everything else is a change to the library specifically. But just check that everything is working in EK as well as the library! I think we'll follow up with the release timing, but of course merge it in when you're ready. Thanks

**Comment by ZafarKamal123** [comment]
Hey @KevinBatdorf,

This PR seems to be breaking editorskit functionality somehow. Can you please test and confirm if everything works fine for you in editorskit?

**Comment by clubkert** [comment]
Hey @ZafarKamal123 - can you tell us what functionality was breaking for you?

**Comment by munirkamal** [comment]
Hey, @clubkert seems like none of the EK features are appearing/working with this PR.

**Comment by KevinBatdorf** [comment]
I see that now. Nothing is loading at all. I'll familiarize myself with EK features Monday and follow up with a fix.

The odd thing is we only switched the order of the dependency list (in `/includes/class-editorskit-block-assets.php`) so I'm surprised that happens. 

We may need to update EK to remove the dependency on `wp-api` which interfaces with backbone.js and use a Gutenberg approach. I believe there are only a couple instances where it's used so could be simple enough.

**Pull request merged**
